//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_StringData
    {
        public int Id { get; set; }
        public string LineContain { get; set; }
        public Nullable<int> Words { get; set; }
        public Nullable<int> Spaces { get; set; }
        public Nullable<int> Charactors { get; set; }
    }
}
